version: '3'

volumes:
  backend-sync-volume:
    external: true

services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'

  redis:
    image: redis:alpine
    command: ['redis-server', '--bind', '0.0.0.0', '--port', '6379']
    ports:
      - '6379:6379'

  backend:
    build:
      context: sinker-backend
    volumes:
      - ./sinker-backend:/usr/src/app
      - ./sinker-backend/vendor/bundle:/usr/local/bundle
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development
      CORS_ORIGINS: 'localhost:3000,127.0.0.1:3000'
      REDIS_URL: redis://redis:6379

  frontend:
    build:
      context: sinker-frontend
    volumes:
      - ./sinker-frontend:/usr/src/app
    ports:
      - '3000:3000'
